<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;


class MenuBuilderSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            [
                'id' => 1,
                'name' => 'main_menu',
                'created_at' => '2026-10-03 00:05:06',
                'updated_at' => '2026-10-03 00:05:06',
            ],
            [
                'id' => 2,
                'name' => 'footer_menu_one',
                'created_at' => '2026-10-03 00:30:26',
                'updated_at' => '2026-10-03 00:30:26',
            ],
            [
                'id' => 3,
                'name' => 'footer_menu_two',
                'created_at' => '2026-10-03 00:31:11',
                'updated_at' => '2026-10-03 00:31:11',
            ],
            [
                'id' => 4,
                'name' => 'footer_menu_three',
                'created_at' => '2026-10-03 00:31:50',
                'updated_at' => '2026-10-03 00:31:50',
            ],
        ];

        DB::table('menus')->insert($menus);

        $menuItems = [
            [
                'id' => 1,
                'label' => 'Home',
                'link' => '/',
                'parent' => 0,
                'sort' => 0,
                'class' => null,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2026-10-02 22:42:55',
                'updated_at' => '2026-10-02 22:44:22',
                'role_id' => 0,
            ],
            [
                'id' => 2,
                'label' => 'About',
                'link' => '/about',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2026-10-02 22:44:22',
                'updated_at' => '2026-10-02 22:45:52',
                'role_id' => 0,
            ],
            [
                'id' => 3,
                'label' => 'Contact',
                'link' => '/contact',
                'parent' => 0,
                'sort' => 2,
                'class' => null,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2026-10-02 22:45:51',
                'updated_at' => '2026-10-02 22:52:09',
                'role_id' => 0,
            ],
            [
                'id' => 4,
                'label' => 'Terms and Conditions',
                'link' => '/terms-and-condistions',
                'parent' => 0,
                'sort' => 4,
                'class' => null,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2026-10-02 22:52:09',
                'updated_at' => '2026-10-03 00:46:54',
                'role_id' => 0,
            ],
            [
                'id' => 5,
                'label' => 'Blogs',
                'link' => '/blogs',
                'parent' => 0,
                'sort' => 3,
                'class' => null,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2026-10-02 22:54:01',
                'updated_at' => '2026-10-03 00:46:54',
                'role_id' => 0,
            ],
            [
                'id' => 7,
                'label' => 'Payment',
                'link' => '/payment-methods',
                'parent' => 0,
                'sort' => 0,
                'class' => null,
                'menu' => 3,
                'depth' => 0,
                'created_at' => '2026-10-03 00:00:41',
                'updated_at' => '2026-10-03 00:27:26',
                'role_id' => 0,
            ],
            [
                'id' => 8,
                'label' => 'Privacy Policy',
                'link' => '/privacy-policy',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 3,
                'depth' => 0,
                'created_at' => '2026-10-03 00:02:28',
                'updated_at' => '2026-10-03 00:03:16',
                'role_id' => 0,
            ],
            [
                'id' => 10,
                'label' => 'Home',
                'link' => '/',
                'parent' => 0,
                'sort' => 0,
                'class' => null,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2026-10-03 07:14:59',
                'updated_at' => '2026-10-03 07:15:25',
                'role_id' => 0,
            ],
            [
                'id' => 11,
                'label' => 'About',
                'link' => '/about',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2026-10-03 07:15:24',
                'updated_at' => '2026-10-03 07:16:07',
                'role_id' => 0,
            ],
            [
                'id' => 12,
                'label' => 'Chefs',
                'link' => '/chef',
                'parent' => 20,
                'sort' => 4,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'created_at' => '2026-10-03 07:16:07',
                'updated_at' => '2026-10-03 08:04:20',
                'role_id' => 0,
            ],
            [
                'id' => 13,
                'label' => 'Blogs',
                'link' => '/blogs',
                'parent' => 0,
                'sort' => 2,
                'class' => null,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2026-10-03 07:16:27',
                'updated_at' => '2026-10-03 07:36:24',
                'role_id' => 0,
            ],
            [
                'id' => 14,
                'label' => 'Contact',
                'link' => '/contact',
                'parent' => 0,
                'sort' => 10,
                'class' => null,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2026-10-03 07:16:55',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 15,
                'label' => 'Testimonials',
                'link' => '/testimonial',
                'parent' => 20,
                'sort' => 7,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'created_at' => '2026-10-03 07:17:59',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 16,
                'label' => 'Privacy Policy',
                'link' => '/privacy-policy',
                'parent' => 20,
                'sort' => 8,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'created_at' => '2026-10-03 07:19:39',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 17,
                'label' => 'Terms And Conditions',
                'link' => '/terms-and-condistions',
                'parent' => 20,
                'sort' => 9,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'created_at' => '2026-10-03 07:21:24',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 18,
                'label' => 'Payment',
                'link' => '/payment-methods',
                'parent' => 20,
                'sort' => 6,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'created_at' => '2026-10-03 07:22:29',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 19,
                'label' => 'Blog Details',
                'link' => '/blogs',
                'parent' => 20,
                'sort' => 5,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'created_at' => '2026-10-03 07:25:39',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 20,
                'label' => 'Pages',
                'link' => '#',
                'parent' => 0,
                'sort' => 3,
                'class' => null,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2026-10-03 07:29:26',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
            [
                'id' => 21,
                'label' => 'Menu',
                'link' => '/products',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2026-10-03 07:29:26',
                'updated_at' => '2026-10-03 08:02:07',
                'role_id' => 0,
            ],
        ];

        DB::table('menu_items')->insert($menuItems);
    }
}
